# Generated by Django 3.2.3 on 2021-06-22 13:20

import apps.facilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.facilities.models.facility_logo_file_path_func),
        ),
    ]
