# Generated by Django 3.2.3 on 2021-06-05 09:37

import apps.facility_tenant.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, verbose_name='Gender')),
                ('eye_color', models.CharField(choices=[('BLK', 'Black'), ('BLU', 'Blue'), ('BRO', 'Brown'), ('GRY', 'Gray'), ('GRN', 'Green'), ('HAZ', 'Hazel'), ('MAR', 'Maroon'), ('MUL', 'Multi-Colored'), ('PNK', 'PNK'), ('XXX', 'Unknown')], default='XXX', max_length=24, verbose_name='Eye Color')),
                ('hair_color', models.CharField(choices=[('BAL', 'Bald'), ('BLK', 'Black'), ('BLN', 'Blonde or strawberry'), ('BRO', 'Brown'), ('GRY', 'Gray or partially gray'), ('GRN', 'Green'), ('ONG', 'Orange'), ('PLE', 'Purple'), ('PNK', 'Pink'), ('RED', 'Red or auburn'), ('SDY', 'Sandy'), ('WHI', 'White'), ('XXX', 'Unknown')], default='XXX', max_length=24, verbose_name='Hair Color')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('o', 'Other'), ('m', 'Male'), ('f', 'Female')], default='o', max_length=1, verbose_name='Gender')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.facility_tenant.models.user_profile_avatar_file_path_func, verbose_name='Avatar')),
            ],
        ),
    ]
