# Generated by Django 3.2.4 on 2021-06-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_tenant', '0002_auto_20210626_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('BLK', 'Black'), ('BLU', 'Blue'), ('BRO', 'Brown'), ('GRY', 'Gray'), ('GRN', 'Green'), ('HAZ', 'Hazel'), ('MAR', 'Maroon'), ('MUL', 'Multi-Colored'), ('PNK', 'PNK'), ('XXX', 'Unknown')], default='XXX', max_length=24, null=True, verbose_name='Eye Color'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('BAL', 'Bald'), ('BLK', 'Black'), ('BLN', 'Blonde or strawberry'), ('BRO', 'Brown'), ('GRY', 'Gray or partially gray'), ('GRN', 'Green'), ('ONG', 'Orange'), ('PLE', 'Purple'), ('PNK', 'Pink'), ('RED', 'Red or auburn'), ('SDY', 'Sandy'), ('WHI', 'White'), ('XXX', 'Unknown')], default='XXX', max_length=24, null=True, verbose_name='Hair Color'),
        ),
    ]
